export default [
  {
    inputs: [
      { internalType: 'address', name: '_implementation', type: 'address' },
      { internalType: 'address', name: '_xhiftToken', type: 'address' },
      { internalType: 'address', name: '_creditLetterNFT', type: 'address' },
      { internalType: 'address', name: '_treasury', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'AccessControlBadConfirmation', type: 'error' },
  {
    inputs: [
      { internalType: 'address', name: 'account', type: 'address' },
      { internalType: 'bytes32', name: 'neededRole', type: 'bytes32' },
    ],
    name: 'AccessControlUnauthorizedAccount',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'bps', type: 'uint256' },
      { internalType: 'uint256', name: 'maxBps', type: 'uint256' },
    ],
    name: 'CashbackBpsTooHigh',
    type: 'error',
  },
  { inputs: [], name: 'CloneCreationFailed', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'length', type: 'uint256' },
      { internalType: 'uint256', name: 'maxLength', type: 'uint256' },
    ],
    name: 'DescriptionTooLong',
    type: 'error',
  },
  { inputs: [], name: 'EmptyPoolName', type: 'error' },
  { inputs: [], name: 'FailedDeployment', type: 'error' },
  { inputs: [], name: 'InitializationFailed', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'balance', type: 'uint256' },
      { internalType: 'uint256', name: 'needed', type: 'uint256' },
    ],
    name: 'InsufficientBalance',
    type: 'error',
  },
  { inputs: [], name: 'InvalidActivator', type: 'error' },
  { inputs: [], name: 'InvalidAddress', type: 'error' },
  { inputs: [], name: 'InvalidAssetLocation', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'value', type: 'uint256' },
      { internalType: 'uint256', name: 'minValue', type: 'uint256' },
      { internalType: 'uint256', name: 'maxValue', type: 'uint256' },
    ],
    name: 'InvalidAssetValue',
    type: 'error',
  },
  { inputs: [], name: 'InvalidCashbackConfig', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'coverage', type: 'uint256' },
      { internalType: 'uint256', name: 'assetValue', type: 'uint256' },
    ],
    name: 'InvalidCoverageAmount',
    type: 'error',
  },
  { inputs: [], name: 'InvalidFeeCollector', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'installment', type: 'uint256' },
      { internalType: 'uint256', name: 'totalValue', type: 'uint256' },
    ],
    name: 'InvalidInstallmentValue',
    type: 'error',
  },
  { inputs: [], name: 'InvalidInsuranceProvider', type: 'error' },
  {
    inputs: [{ internalType: 'uint256', name: 'maxTime', type: 'uint256' }],
    name: 'InvalidMaxActivationTime',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'months', type: 'uint256' }],
    name: 'InvalidMinParticipationMonths',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'consecutive', type: 'uint256' },
      { internalType: 'uint256', name: 'total', type: 'uint256' },
    ],
    name: 'InvalidMissedPaymentsConfig',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'min', type: 'uint256' },
      { internalType: 'uint256', name: 'max', type: 'uint256' },
    ],
    name: 'InvalidParticipantRange',
    type: 'error',
  },
  { inputs: [], name: 'InvalidParticipants', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'minBalance', type: 'uint256' },
      { internalType: 'uint256', name: 'maxBalance', type: 'uint256' },
    ],
    name: 'InvalidReserveConfig',
    type: 'error',
  },
  { inputs: [], name: 'InvalidValue', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'fee', type: 'uint256' },
      { internalType: 'uint256', name: 'maxFee', type: 'uint256' },
    ],
    name: 'InvalidWithdrawalFee',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'fee', type: 'uint256' },
      { internalType: 'uint256', name: 'maxFee', type: 'uint256' },
    ],
    name: 'ManagementFeeTooHigh',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'maxParticipants', type: 'uint256' }],
    name: 'MaxParticipantsTooHigh',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'minParticipants', type: 'uint256' }],
    name: 'MinParticipantsTooLow',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'penalty', type: 'uint256' },
      { internalType: 'uint256', name: 'maxPenalty', type: 'uint256' },
    ],
    name: 'PenaltyTooHigh',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'length', type: 'uint256' },
      { internalType: 'uint256', name: 'maxLength', type: 'uint256' },
    ],
    name: 'PoolNameTooLong',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'bps', type: 'uint256' },
      { internalType: 'uint256', name: 'maxBps', type: 'uint256' },
    ],
    name: 'ReserveBpsTooHigh',
    type: 'error',
  },
  { inputs: [], name: 'RoleGrantFailed', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'startDate', type: 'uint256' },
      { internalType: 'uint256', name: 'currentTime', type: 'uint256' },
    ],
    name: 'StartDateInPast',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'poolId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'poolAddress', type: 'address' },
      { indexed: true, internalType: 'address', name: 'creator', type: 'address' },
      { indexed: false, internalType: 'string', name: 'name', type: 'string' },
    ],
    name: 'PoolCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { indexed: true, internalType: 'bytes32', name: 'previousAdminRole', type: 'bytes32' },
      { indexed: true, internalType: 'bytes32', name: 'newAdminRole', type: 'bytes32' },
    ],
    name: 'RoleAdminChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
    ],
    name: 'RoleGranted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
    ],
    name: 'RoleRevoked',
    type: 'event',
  },
  {
    inputs: [],
    name: 'DEFAULT_ADMIN_ROLE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_ACTIVATION_TIME',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_ASSET_LOCATION_LENGTH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_ASSET_VALUE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_CASHBACK_BPS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_COVERAGE_MULTIPLIER',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_DESCRIPTION_LENGTH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_EARLY_WITHDRAWAL_PENALTY_BPS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_EXCLUSION_PENALTY_BPS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_INSURANCE_PREMIUM_BPS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_LATE_PAYMENT_PENALTY_BPS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_MANAGEMENT_FEE_BPS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_PARTICIPANTS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_PARTICIPATION_MONTHS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_PERFORMANCE_FEE_BPS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_POOL_NAME_LENGTH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_REPLENISHMENT_EXTRA_BPS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_RESERVE_BPS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_WITHDRAWAL_FEE_BPS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MIN_ASSET_VALUE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MIN_PARTICIPANTS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'POOL_CREATOR_ROLE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'START_DATE_BUFFER',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'uint256', name: 'maxParticipants', type: 'uint256' },
          { internalType: 'uint256', name: 'minParticipants', type: 'uint256' },
          { internalType: 'uint256', name: 'installmentValue', type: 'uint256' },
          { internalType: 'uint256', name: 'totalAssetValue', type: 'uint256' },
          { internalType: 'uint256', name: 'startDate', type: 'uint256' },
          { internalType: 'enum IHousingPoolLLC.AssetType', name: 'assetType', type: 'uint8' },
          { internalType: 'string', name: 'assetLocation', type: 'string' },
        ],
        internalType: 'struct IHousingPoolLLC.CorePoolConfig',
        name: 'coreConfig',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint16', name: 'latePaymentPenaltyBps', type: 'uint16' },
          {
            internalType: 'enum IHousingPoolLLC.PaymentMethod',
            name: 'paymentMethod',
            type: 'uint8',
          },
        ],
        internalType: 'struct IHousingPoolLLC.ContributionRules',
        name: 'contributionRules',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint256', name: 'maxConsecutiveMissedPayments', type: 'uint256' },
          { internalType: 'uint256', name: 'maxTotalMissedPayments', type: 'uint256' },
          { internalType: 'uint16', name: 'exclusionPenaltyBps', type: 'uint16' },
          {
            internalType: 'enum IHousingPoolLLC.ExclusionRefundPolicy',
            name: 'refundPolicy',
            type: 'uint8',
          },
        ],
        internalType: 'struct IHousingPoolLLC.ExclusionRules',
        name: 'exclusionRules',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'bool', name: 'withdrawalAllowed', type: 'bool' },
          { internalType: 'uint16', name: 'earlyWithdrawalPenaltyBps', type: 'uint16' },
          { internalType: 'uint256', name: 'minParticipationMonths', type: 'uint256' },
          { internalType: 'uint16', name: 'withdrawalFeeBps', type: 'uint16' },
        ],
        internalType: 'struct IHousingPoolLLC.WithdrawalRules',
        name: 'withdrawalRules',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'bool', name: 'enabled', type: 'bool' },
          { internalType: 'uint16', name: 'cashbackBps', type: 'uint16' },
          { internalType: 'address', name: 'rewardToken', type: 'address' },
          { internalType: 'uint256', name: 'minContributionForCashback', type: 'uint256' },
          { internalType: 'uint256', name: 'cashbackCap', type: 'uint256' },
        ],
        internalType: 'struct IHousingPoolLLC.CashbackConfig',
        name: 'cashbackConfig',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint16', name: 'reserveBps', type: 'uint16' },
          { internalType: 'uint16', name: 'replenishmentExtraBps', type: 'uint16' },
          { internalType: 'uint8', name: 'replenishmentMaxMonths', type: 'uint8' },
          { internalType: 'uint256', name: 'minReserveBalance', type: 'uint256' },
          { internalType: 'uint256', name: 'maxReserveBalance', type: 'uint256' },
        ],
        internalType: 'struct IHousingPoolLLC.ReserveFundConfig',
        name: 'reserveConfig',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint16', name: 'managementFeeBps', type: 'uint16' },
          {
            internalType: 'enum IHousingPoolLLC.FeeChargingScheduleType',
            name: 'chargingSchedule',
            type: 'uint8',
          },
          { internalType: 'address', name: 'feeCollector', type: 'address' },
          { internalType: 'uint16', name: 'performanceFeeBps', type: 'uint16' },
        ],
        internalType: 'struct IHousingPoolLLC.PoolManagementConfig',
        name: 'poolManagement',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'bool', name: 'insuranceEnabled', type: 'bool' },
          { internalType: 'uint16', name: 'insurancePremiumBps', type: 'uint16' },
          { internalType: 'address', name: 'insuranceProvider', type: 'address' },
          { internalType: 'uint256', name: 'coverageAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'deductible', type: 'uint256' },
        ],
        internalType: 'struct IHousingPoolLLC.InsuranceConfig',
        name: 'insuranceConfig',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'bool', name: 'kycRequired', type: 'bool' },
          { internalType: 'bool', name: 'amlRequired', type: 'bool' },
          { internalType: 'address', name: 'complianceOracle', type: 'address' },
          { internalType: 'uint256', name: 'minIdentityScore', type: 'uint256' },
          { internalType: 'string', name: 'jurisdiction', type: 'string' },
        ],
        internalType: 'struct IHousingPoolLLC.ComplianceConfig',
        name: 'complianceConfig',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'address', name: 'oracleAddress', type: 'address' },
          { internalType: 'address', name: 'keeperAddress', type: 'address' },
          { internalType: 'address', name: 'vrfCoordinator', type: 'address' },
          { internalType: 'bytes32', name: 'vrfKeyHash', type: 'bytes32' },
          { internalType: 'uint256', name: 'vrfFee', type: 'uint256' },
        ],
        internalType: 'struct IHousingPoolLLC.BlockchainConfig',
        name: 'blockchainConfig',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint256', name: 'minInitialContributions', type: 'uint256' },
          { internalType: 'uint256', name: 'maxActivationTime', type: 'uint256' },
          { internalType: 'address', name: 'activator', type: 'address' },
        ],
        internalType: 'struct IHousingPoolLLC.PoolActivationConfig',
        name: 'activationConfig',
        type: 'tuple',
      },
    ],
    name: 'createPool',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'creditLetterNFT',
    outputs: [{ internalType: 'contract ICreditLetterNFT', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
    name: 'getRoleAdmin',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'grantRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'hasRole',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'implementation',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'poolCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'pools',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'callerConfirmation', type: 'address' },
    ],
    name: 'renounceRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'revokeRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'treasury',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'xhiftToken',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
];
